/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

export type AddressInput = { value: string };

export type AddressOutput = { value: string };

interface CounterContractAbiInterface extends Interface {
  functions: {
    count: FunctionFragment;
    registered: FunctionFragment;
    increment: FunctionFragment;
    register: FunctionFragment;
  };

  encodeFunctionData(functionFragment: "count", values?: undefined): Uint8Array;
  encodeFunctionData(
    functionFragment: "registered",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "increment",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressInput, string]
  ): Uint8Array;

  decodeFunctionData(functionFragment: "count", data: BytesLike): DecodedValue;
  decodeFunctionData(
    functionFragment: "registered",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "increment",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "register",
    data: BytesLike
  ): DecodedValue;
}

export class CounterContractAbi extends Contract {
  interface: CounterContractAbiInterface;
  functions: {
    count: InvokeFunction<[], BN>;

    registered: InvokeFunction<[], string>;

    increment: InvokeFunction<[], void>;

    register: InvokeFunction<[address_owner: AddressInput, name: string], void>;
  };
}
