/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

export type AddressInput = { value: string };

export type AddressOutput = { value: string };

interface CounterContractAbiInterface extends Interface {
  functions: {
    get_name: FunctionFragment;
    register: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "get_name",
    values: [string]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressInput, string]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "get_name",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "register",
    data: BytesLike
  ): DecodedValue;
}

export class CounterContractAbi extends Contract {
  interface: CounterContractAbiInterface;
  functions: {
    get_name: InvokeFunction<[name: string], AddressOutput>;

    register: InvokeFunction<[address_owner: AddressInput, name: string], void>;
  };
}
